/**
 * @file pokemonLocations.js
 * @description Comprehensive list of Pokémon locations for room ID generation
 * @version 2.0.0
 * @author Meta-PTCG Development Team
 */

/**
 * Extensive list of Pokémon locations from various regions and games
 * Organized by region and significance for diverse room ID generation
 * @type {string[]}
 */
export const POKEMON_LOCATIONS = [
  // Kanto Regions
  'Pallet Town',
  'Viridian City',
  'Pewter City',
  'Cerulean City',
  'Vermilion City',
  'Lavender Town',
  'Celadon City',
  'Fuchsia City',
  'Saffron City',
  'Cinnabar Island',
  'Mt. Moon',
  'Victory Road',
  'Diglett Cave',
  'Seafoam Islands',
  'Rocket Hideout',
  'Pokemon Mansion',

  // Johto Regions
  'New Bark Town',
  'Cherrygrove City',
  'Violet City',
  'Azalea Town',
  'Goldenrod City',
  'Ecruteak City',
  'Olivine City',
  'Cianwood City',
  'Mahogany Town',
  'Blackthorn City',
  'Ruins of Alph',
  'Bell Tower',
  'Whirl Islands',
  'Mt. Silver',
  'Lake of Rage',
  'National Park',

  // Hoenn Regions
  'Littleroot Town',
  'Oldale Town',
  'Petalburg City',
  'Rustboro City',
  'Dewford Town',
  'Slateport City',
  'Mauville City',
  'Verdanturf Town',
  'Fallarbor Town',
  'Fortree City',
  'Lilycove City',
  'Mossdeep City',
  'Sootopolis City',
  'Ever Grande City',
  'Meteor Falls',
  'Sky Pillar',
  'Mt. Chimney',
  'Weather Institute',
  'Sea Mauville',
  'Mirage Island',

  // Sinnoh Regions
  'Twinleaf Town',
  'Sandgem Town',
  'Jubilife City',
  'Oreburgh City',
  'Floaroma Town',
  'Eterna City',
  'Hearthome City',
  'Solaceon Town',
  'Veilstone City',
  'Pastoria City',
  'Celestic Town',
  'Canalave City',
  'Snowpoint City',
  'Sunyshore City',
  'Valley Windworks',
  'Solaceon Ruins',
  'Iron Island',
  'Lake Verity',
  'Lake Valor',
  'Lake Acuity',

  // Unova Regions
  'Nuvema Town',
  'Accumula Town',
  'Striaton City',
  'Nacrene City',
  'Castelia City',
  'Nimbasa City',
  'Driftveil City',
  'Mistralton City',
  'Icirrus City',
  'Opelucid City',
  'Black City',
  'White Forest',
  'Twist Mountain',
  'Dragonspiral Tower',
  'Clay Tunnel',
  'Pinwheel Forest',

  // Kalos Regions
  'Vaniville Town',
  'Aquacorde Town',
  'Santalune City',
  'Lumiose City',
  'Camphrier Town',
  'Parfum Palace',
  'Laverre City',
  'Dendemille Town',
  'Anistar City',
  'Couriway Town',
  'Snowbelle City',
  'Kiloude City',
  'Coumarine City',
  'Geosenge Town',
  'Reflection Cave',
  'Battle Chateau',

  // Alola Regions
  'Iki Town',
  "Hau'oli City",
  'Heahea City',
  'Konikoni City',
  'Malie City',
  'Tapu Village',
  'Altar of the Sunne',
  'Altar of the Moone',
  'Melemele Meadow',
  'Lush Jungle',
  'Akala Outskirts',
  'Exeggutor Island',
  'Aether Paradise',
  'Ultra Village',
  'Mount Lanakila',
  'Resolution Cave',

  // Galar Regions
  'Postwick',
  'Wedgehurst',
  'Turffield',
  'Hulbury',
  'Motostoke',
  'Hammerlocke',
  'Wyndon',
  'Circhester',
  'Stow-on-Side',
  'Ballonlea',
  'Snowslide Slope',
  'Giants Bed',
  'Dyna Tree Hill',
  'Rose Tower',
  'Energy Plant',
  'Lake of Outrage',
  'Muscle Hill',
  'Galar Mine',

  // Paldea Regions
  'Cabo Poco',
  'Cortondo',
  'Los Platos',
  'Medali',
  'Cascarrafa',
  'Levincia',
  'Messir',
  'Porto Marinada',
  'Alfornada',
  'Montenevera',
  'Team Star Base',
  'Glaseado Mountain',
  'Poco Path Lighthouse',
  'North Province',
  'East Province',
  'South Province',
  'Casseroya Lake',

  // Legendary and Mythical Locations
  'Sinjoh Ruins',
  'Spear Pillar',
  'Distortion World',
  'Hall of Origin',
  'Legendary Shrine',
  'Poké Pelago',
  'Orre Region',
  'Revorама Region',

  // Additional Unique Locations
  'Pokemon League',
  'Safari Zone',
  'Unknown Dungeon',
  'Battle Frontier',
  'Pokemon World Tournament',
  'Battle Resort',
  'Parfum Palace',
  'Cerulean Cave',
  'Mt. Coronet',
  'Hoenn Battle Frontier',

  // Special Event and Spin-off Locations
  'Pokemon Stadium',
  'Johto Safari Zone',
  'Ranger Union',
  'Pokemon Colosseum',
  'XD Laboratory',
  'Mystery Dungeon',
  'Ranger School',
  'Oblivia Ranger Base',
  'Fiore Region',

  // Unique Landscape Locations
  'Crystal Cavern',
  'Volcanic Island',
  'Ancient Ruins',
  'Misty Forest',
  'Frozen Tundra',
  'Desert Oasis',
  'Mystic Archipelago',
  'Starlight Peak',
  'Moonlight Plateau',
  'Sunrise Valley',
  'Thunderstorm Plains',

  // Mythical and Legendary Encounter Locations
  'Serpent Cave',
  "Dragon's Den",
  'Mystical Grove',
  'Celestial Peak',
  'Temporal Tower',
  'Dimensional Rift',
  'Cosmic Observatory',
  'Primordial Landscape',
  'Legendary Sanctum',
];
