/**
 * Comprehensive list of Pokémon locations from various regions
 * Used for generating unique room IDs
 */
export const POKEMON_LOCATIONS = [
  // Kanto Regions
  'Pallet Town',
  'Viridian City',
  'Pewter City',
  'Cerulean City',
  'Vermilion City',
  'Lavender Town',
  'Celadon City',
  'Fuchsia City',
  'Saffron City',
  'Cinnabar Island',
  'Mt. Moon',
  'Victory Road',
  'Diglett Cave',
  'Seafoam Islands',
  'Rocket Hideout',
  'Pokemon Mansion',

  // Johto Regions
  'New Bark Town',
  'Cherrygrove City',
  'Violet City',
  'Azalea Town',
  'Goldenrod City',
  'Ecruteak City',
  'Olivine City',
  'Cianwood City',
  'Mahogany Town',
  'Blackthorn City',
  'Ruins of Alph',
  'Bell Tower',
  'Whirl Islands',
  'Mt. Silver',
  'Lake of Rage',
  'National Park',

  // Hoenn Regions
  'Littleroot Town',
  'Oldale Town',
  'Petalburg City',
  'Rustboro City',
  'Dewford Town',
  'Slateport City',
  'Mauville City',
  'Verdanturf Town',
  'Fallarbor Town',
  'Fortree City',
  'Lilycove City',
  'Mossdeep City',
  'Sootopolis City',
  'Ever Grande City',
  'Meteor Falls',
  'Sky Pillar',
  'Mt. Chimney',
  'Weather Institute',
  'Sea Mauville',
  'Mirage Island',

  // Sinnoh Regions
  'Twinleaf Town',
  'Sandgem Town',
  'Jubilife City',
  'Oreburgh City',
  'Floaroma Town',
  'Eterna City',
  'Hearthome City',
  'Solaceon Town',
  'Veilstone City',
  'Pastoria City',
  'Celestic Town',
  'Canalave City',
  'Snowpoint City',
  'Sunyshore City',
  'Valley Windworks',
  'Solaceon Ruins',
  'Iron Island',
  'Lake Verity',
  'Lake Valor',
  'Lake Acuity',

  // Unova Regions
  'Nuvema Town',
  'Accumula Town',
  'Striaton City',
  'Nacrene City',
  'Castelia City',
  'Nimbasa City',
  'Driftveil City',
  'Mistralton City',
  'Icirrus City',
  'Opelucid City',
  'Black City',
  'White Forest',
  'Twist Mountain',
  'Dragonspiral Tower',
  'Clay Tunnel',
  'Pinwheel Forest',

  // Kalos Regions
  'Vaniville Town',
  'Aquacorde Town',
  'Santalune City',
  'Lumiose City',
  'Camphrier Town',
  'Parfum Palace',
  'Laverre City',
  'Dendemille Town',
  'Anistar City',
  'Couriway Town',
  'Snowbelle City',
  'Kiloude City',
  'Coumarine City',
  'Geosenge Town',
  'Reflection Cave',
  'Battle Chateau',

  // Alola Regions
  'Iki Town',
  "Hau'oli City",
  'Heahea City',
  'Konikoni City',
  'Malie City',
  'Tapu Village',
  'Altar of the Sunne',
  'Altar of the Moone',
  'Melemele Meadow',
  'Lush Jungle',
  'Akala Outskirts',
  'Exeggutor Island',
  'Aether Paradise',
  'Ultra Village',
  'Mount Lanakila',
  'Resolution Cave',

  // Galar Regions
  'Postwick',
  'Wedgehurst',
  'Turffield',
  'Hulbury',
  'Motostoke',
  'Hammerlocke',
  'Wyndon',
  'Circhester',
  'Stow-on-Side',
  'Ballonlea',
  'Snowslide Slope',
  "Giant's Bed",
  'Dyna Tree Hill',
  'Rose Tower',
  'Energy Plant',
  'Lake of Outrage',
  'Muscle Hill',
  'Galar Mine',

  // Paldea Regions
  'Cabo Poco',
  'Cortondo',
  'Los Platos',
  'Medali',
  'Cascarrafa',
  'Levincia',
  'Messir',
  'Porto Marinada',
  'Alfornada',
  'Montenevera',
  'Team Star Base',
  'Glaseado Mountain',
  'Poco Path Lighthouse',
  'North Province',
  'East Province',
  'South Province',
  'Casseroya Lake',

  // Additional Unique Locations
  'Pokemon League',
  'Safari Zone',
  'Unknown Dungeon',
  'Distortion World',
  'Pokemon World Tournament',
  'Battle Resort',
  'Parfum Palace',
  'Cerulean Cave',
  'Mt. Coronet',
  'Hoenn Battle Frontier',
];
